#!/usr/bin/env python3
"""Pack assets/i18n/*.json into C tables. Add a language by dropping <code>.json
and listing the code in catalog.json langs."""
from __future__ import annotations

import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
I18N_DIR = os.path.join(ROOT, "assets", "i18n")
OUT_H = os.path.join(ROOT, "out", "i18n_gen.h")
OUT_C = os.path.join(ROOT, "out", "i18n_data.c")


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def key_to_msg(key: str) -> str:
    return "MSG_" + key.upper()


def lang_enum(code: str) -> str:
    return "LANG_" + code.upper().replace("-", "_")


def load_json(path: str):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main() -> int:
    catalog_path = os.path.join(I18N_DIR, "catalog.json")
    catalog = load_json(catalog_path)
    langs = catalog["langs"]
    keys = catalog["keys"]
    if not langs or not keys:
        print("gen_i18n: catalog.json needs langs and keys", file=sys.stderr)
        return 1

    packs = []
    for code in langs:
        path = os.path.join(I18N_DIR, f"{code}.json")
        if not os.path.isfile(path):
            print(f"gen_i18n: missing {path}", file=sys.stderr)
            return 1
        data = load_json(path)
        strings = data.get("strings", {})
        missing = [k for k in keys if k not in strings]
        if missing:
            print(f"gen_i18n: {code}.json missing keys: {', '.join(missing)}",
                  file=sys.stderr)
            return 1
        weekdays = data.get("weekdays", [])
        months = data.get("months", [])
        abbr = data.get("months_abbr", [])
        if len(weekdays) != 7 or len(months) != 12 or len(abbr) != 12:
            print(f"gen_i18n: {code}.json needs 7 weekdays and 12 months",
                  file=sys.stderr)
            return 1
        date = data.get("date", {})
        packs.append({
            "code": code,
            "name": data.get("name", code),
            "day_first": 1 if date.get("day_first", True) else 0,
            "join": date.get("join", " "),
            "weekdays": weekdays,
            "months": months,
            "abbr": abbr,
            "strings": strings,
        })

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    h = []
    h.append("/* Generated by tools/gen_i18n.py — do not edit. */")
    h.append("#ifndef CORDOS_I18N_GEN_H")
    h.append("#define CORDOS_I18N_GEN_H")
    h.append("")
    h.append(f"#define I18N_LANG_COUNT {len(packs)}u")
    h.append("")
    h.append("enum lang_id {")
    for i, p in enumerate(packs):
        comma = "," if i + 1 < len(packs) else ""
        h.append(f"    {lang_enum(p['code'])} = {i}{comma}")
    h.append("};")
    h.append("")
    h.append("enum msg_id {")
    for i, key in enumerate(keys):
        comma = "," if i + 1 < len(keys) else ""
        h.append(f"    {key_to_msg(key)} = {i}{comma}")
    h.append("};")
    h.append("")
    h.append(f"#define MSG_COUNT {len(keys)}")
    h.append("")
    h.append("#endif")
    h.append("")
    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h))

    c = []
    c.append("/* Generated by tools/gen_i18n.py — do not edit. */")
    c.append("#include \"i18n.h\"")
    c.append("")
    c.append("const char *const i18n_codes[I18N_LANG_COUNT] = {")
    c.append("    " + ", ".join(c_str(p["code"]) for p in packs))
    c.append("};")
    c.append("")
    c.append("const char *const i18n_names[I18N_LANG_COUNT] = {")
    c.append("    " + ", ".join(c_str(p["name"]) for p in packs))
    c.append("};")
    c.append("")
    c.append("const u8 i18n_day_first[I18N_LANG_COUNT] = {")
    c.append("    " + ", ".join(str(p["day_first"]) + "u" for p in packs))
    c.append("};")
    c.append("")
    c.append("const char *const i18n_date_joins[I18N_LANG_COUNT] = {")
    c.append("    " + ", ".join(c_str(p["join"]) for p in packs))
    c.append("};")
    c.append("")
    c.append("const char *const i18n_weekdays[I18N_LANG_COUNT][7] = {")
    for p in packs:
        c.append("    { " + ", ".join(c_str(s) for s in p["weekdays"]) + " },")
    c.append("};")
    c.append("")
    c.append("const char *const i18n_months[I18N_LANG_COUNT][12] = {")
    for p in packs:
        c.append("    { " + ", ".join(c_str(s) for s in p["months"]) + " },")
    c.append("};")
    c.append("")
    c.append("const char *const i18n_months_abbr[I18N_LANG_COUNT][12] = {")
    for p in packs:
        c.append("    { " + ", ".join(c_str(s) for s in p["abbr"]) + " },")
    c.append("};")
    c.append("")
    c.append("const char *const i18n_strings[I18N_LANG_COUNT][MSG_COUNT] = {")
    for p in packs:
        c.append("    {")
        for key in keys:
            c.append(f"        [{key_to_msg(key)}] = {c_str(p['strings'][key])},")
        c.append("    },")
    c.append("};")
    c.append("")
    with open(OUT_C, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(c))

    print(f"gen_i18n: {len(packs)} langs, {len(keys)} keys -> {OUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
